//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace latcam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConektaCards
    {
        public string UserID { get; set; }
        public string CardToken { get; set; }
        public string Last4 { get; set; }
        public int Exp_Month { get; set; }
        public int Exp_Year { get; set; }
        public string Brand { get; set; }
    
        public virtual ConektaUsers ConektaUsers { get; set; }
    }
}
