//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace latcam.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class latincamEntities : DbContext
    {
        public latincamEntities()
            : base("name=latincamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AccountType> AccountType { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<ConektaCards> ConektaCards { get; set; }
        public virtual DbSet<Profile> Profile { get; set; }
        public virtual DbSet<Streaming> Streaming { get; set; }
        public virtual DbSet<StreamingCamera> StreamingCamera { get; set; }
        public virtual DbSet<Subscriptions> Subscriptions { get; set; }
        public virtual DbSet<ConektaUsers> ConektaUsers { get; set; }
        public virtual DbSet<Favorites> Favorites { get; set; }
        public virtual DbSet<StreamingLikes> StreamingLikes { get; set; }
        public virtual DbSet<CamerasSuggestions> CamerasSuggestions { get; set; }
        public virtual DbSet<StreamingSuggestions> StreamingSuggestions { get; set; }
        public virtual DbSet<TopActiveRandomStreamingView> TopActiveRandomStreamingView { get; set; }
        public virtual DbSet<TopMostLikeStreamingView> TopMostLikeStreamingView { get; set; }
        public virtual DbSet<TopMostRatedStreamingView> TopMostRatedStreamingView { get; set; }
        public virtual DbSet<TopMostSuggestStreamingView> TopMostSuggestStreamingView { get; set; }
        public virtual DbSet<TopViewsStreamingView> TopViewsStreamingView { get; set; }
        public virtual DbSet<TopViewsCamerasView> TopViewsCamerasView { get; set; }
        public virtual DbSet<CurrentUsers> CurrentUsers { get; set; }
        public virtual DbSet<CameraLikes> CameraLikes { get; set; }
        public virtual DbSet<StreamingRatings> StreamingRatings { get; set; }
        public virtual DbSet<CameraRatings> CameraRatings { get; set; }
        public virtual DbSet<PaypalPlans> PaypalPlans { get; set; }
    }
}
