//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace latcam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriptions
    {
        public string Id { get; set; }
        public string UserId { get; set; }
        public int SubscriptionType { get; set; }
        public System.DateTime SubscriptionDate { get; set; }
        public Nullable<System.DateTime> SubscriptionEndDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
