//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace latcam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopViewsCamerasView
    {
        public string Id { get; set; }
        public string StreamingId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string StreamUrl { get; set; }
        public bool AllowPublic { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Views { get; set; }
    }
}
